import type { ReferenceSource, SourceConfig } from "../../shared/schemas/index.js";

export const category = "ai-engineering" as const;

/**
 * Every source's cutoff below was approved as a single batch decision
 * (PRD §22) rather than guessed per source: 30 days back from onboarding,
 * enough real content on first sync without approaching the 200-item
 * volume guard (PRD §18.6).
 */
const INITIAL_SYNC_FROM = "2026-07-18";

export const sources: SourceConfig[] = [
  // --- Blogs (feed adapter) ---
  {
    id: "openai-news",
    name: "OpenAI News/Blog",
    category,
    kind: "feed",
    url: "https://openai.com/news/rss.xml",
    adapter: "feed",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "active",
    tags: ["openai"],
  },
  {
    id: "openai-cookbook",
    name: "OpenAI Cookbook",
    category,
    kind: "feed",
    // cookbook.openai.com now redirects into developers.openai.com/cookbook;
    // this is that site's one sitewide feed (guides, videos, and cookbook
    // examples mixed together) — verified live, no cookbook-only feed exists.
    url: "https://developers.openai.com/rss.xml",
    adapter: "feed",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "active",
    tags: ["openai", "cookbook"],
  },
  {
    id: "github-ai-ml-blog",
    name: "GitHub AI & ML Blog",
    category,
    kind: "feed",
    url: "https://github.blog/ai-and-ml/feed/",
    adapter: "feed",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "active",
    tags: ["github"],
  },
  {
    id: "claude-platform-release-notes",
    name: "Claude Platform release notes",
    category,
    kind: "feed",
    url: "https://platform.claude.com/docs/en/release-notes/feed.xml",
    adapter: "feed",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "active",
    tags: ["anthropic", "claude"],
  },
  {
    id: "weaviate-blog",
    name: "Weaviate Blog",
    category,
    kind: "feed",
    url: "https://weaviate.io/blog/rss.xml",
    adapter: "feed",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "active",
    tags: ["vector-db", "weaviate"],
  },
  {
    id: "qdrant-blog",
    name: "Qdrant Blog",
    category,
    kind: "feed",
    url: "https://qdrant.tech/blog/index.xml",
    adapter: "feed",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "active",
    tags: ["vector-db", "qdrant"],
  },
  {
    id: "ollama-blog",
    name: "Ollama Blog",
    category,
    kind: "feed",
    url: "https://ollama.com/blog/rss.xml",
    adapter: "feed",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "active",
    tags: ["ollama", "local-llm"],
  },
  {
    id: "lm-studio-updates",
    name: "LM Studio updates",
    category,
    kind: "feed",
    url: "https://lmstudio.ai/rss.xml",
    adapter: "feed",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "active",
    tags: ["lm-studio", "local-llm"],
  },
  {
    id: "huggingface-blog",
    name: "Hugging Face Blog",
    category,
    kind: "feed",
    url: "https://huggingface.co/blog/feed.xml",
    adapter: "feed",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "active",
    tags: ["huggingface"],
  },
  {
    id: "simon-willison",
    name: "Simon Willison",
    category,
    kind: "feed",
    url: "https://simonwillison.net/atom/everything/",
    adapter: "feed",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "active",
    tags: ["independent", "llm"],
  },
  {
    id: "eugene-yan",
    name: "Eugene Yan",
    category,
    kind: "feed",
    url: "https://eugeneyan.com/rss/",
    adapter: "feed",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "active",
    tags: ["independent", "ml"],
  },
  {
    id: "hamel-husain",
    name: "Hamel Husain",
    category,
    kind: "feed",
    url: "https://hamel.dev/index.xml",
    adapter: "feed",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "active",
    tags: ["independent", "llm"],
  },
  {
    id: "lil-log",
    name: "Lil'Log",
    category,
    kind: "feed",
    url: "https://lilianweng.github.io/index.xml",
    adapter: "feed",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "active",
    tags: ["independent", "ml"],
  },
  {
    id: "fast-ai-blog",
    name: "fast.ai Blog",
    category,
    kind: "feed",
    url: "https://www.fast.ai/index.xml",
    adapter: "feed",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "active",
    tags: ["fast-ai", "deep-learning"],
  },
  {
    id: "latent-space",
    name: "Latent Space",
    category,
    kind: "feed",
    url: "https://www.latent.space/feed",
    adapter: "feed",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "active",
    tags: ["independent", "podcast"],
  },
  {
    id: "jason-liu-instructor",
    name: "Jason Liu / Instructor",
    category,
    kind: "feed",
    url: "https://jxnl.co/feed_rss_created.xml",
    adapter: "feed",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "active",
    tags: ["independent", "instructor"],
  },

  // --- Newsletter: one issue per item, via the feed adapter + a label
  // override (#30). ---
  {
    id: "ai-news-newsletter",
    name: "AI News",
    category,
    kind: "feed",
    // buttondown.com/ainews (named in the issue) has moved and stopped
    // publishing — its feed's own latest item announces the move. The
    // newsletter's real, live feed is now at news.smol.ai — verified live
    // during onboarding.
    url: "https://news.smol.ai/rss.xml",
    adapter: "feed",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "active",
    tags: ["newsletter", "ai-news"],
    filters: { label: "Announcement" },
  },

  // --- Stable releases (github-release adapter) ---
  {
    id: "claude-code-releases",
    name: "Claude Code changelog and stable releases",
    category,
    kind: "github-release",
    url: "https://github.com/anthropics/claude-code",
    adapter: "github-release",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "active",
    tags: ["anthropic", "claude-code"],
  },
  {
    id: "openai-agents-sdk-ts-releases",
    name: "OpenAI Agents SDK for TypeScript releases",
    category,
    kind: "github-release",
    url: "https://github.com/openai/openai-agents-js",
    adapter: "github-release",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "active",
    tags: ["openai", "agents-sdk"],
  },
  {
    id: "mcp-spec-releases",
    name: "Model Context Protocol spec releases",
    category,
    kind: "github-release",
    url: "https://github.com/modelcontextprotocol/modelcontextprotocol",
    adapter: "github-release",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "active",
    tags: ["mcp"],
  },
  {
    id: "mcp-typescript-sdk-releases",
    name: "MCP TypeScript SDK releases",
    category,
    kind: "github-release",
    url: "https://github.com/modelcontextprotocol/typescript-sdk",
    adapter: "github-release",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "active",
    tags: ["mcp", "typescript"],
  },
  {
    id: "langgraphjs-releases",
    name: "LangGraph JS stable releases",
    category,
    kind: "github-release",
    url: "https://github.com/langchain-ai/langgraphjs",
    adapter: "github-release",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "active",
    tags: ["langchain", "langgraph"],
  },
  {
    id: "ollama-releases",
    name: "Ollama stable releases",
    category,
    kind: "github-release",
    url: "https://github.com/ollama/ollama",
    adapter: "github-release",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "active",
    tags: ["ollama", "local-llm"],
  },
  {
    id: "mastra-releases",
    name: "Mastra official updates",
    category,
    kind: "github-release",
    url: "https://github.com/mastra-ai/mastra",
    adapter: "github-release",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "active",
    tags: ["mastra", "agents"],
  },

  // --- Virtual source (#27): shares the URL/adapter of the real GitHub
  // Changelog site, NOT the GitHub AI & ML Blog above. Verified live that
  // the Copilot label already discriminates cleanly by title. ---
  {
    id: "github-copilot-changelog",
    name: "GitHub Copilot changelog",
    category,
    kind: "feed",
    url: "https://github.blog/changelog/feed/",
    adapter: "feed",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "active",
    tags: ["github", "copilot"],
    filters: { virtualScope: { titleContains: "Copilot" } },
  },

  // --- Planned: near-continuous per-package/per-day release tags (dozens
  // to 100 in a 30-day window even after excluding drafts/prereleases) —
  // verified live against the GitHub API during onboarding, same pattern
  // as TanStack in config/sources/web-core.ts. The existing github-release
  // adapter has no per-package curation, so activating these as-is would
  // flood the feed or trip the volume guard. Needs a curated/filtered
  // release adapter, not yet built. ---
  {
    id: "openai-codex-releases",
    name: "OpenAI Codex stable releases",
    category,
    kind: "github-release",
    url: "https://github.com/openai/codex",
    adapter: "github-release-curated",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "planned",
    tags: ["openai", "codex"],
  },
  {
    id: "langchainjs-releases",
    name: "LangChain JS stable releases",
    category,
    kind: "github-release",
    url: "https://github.com/langchain-ai/langchainjs",
    adapter: "github-release-curated",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "planned",
    tags: ["langchain"],
  },
  {
    id: "vercel-ai-sdk-releases",
    name: "Vercel AI SDK stable releases",
    category,
    kind: "github-release",
    url: "https://github.com/vercel/ai",
    adapter: "github-release-curated",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "planned",
    tags: ["vercel", "ai-sdk"],
  },
  {
    id: "assistant-ui-releases",
    name: "assistant-ui official updates",
    category,
    kind: "github-release",
    url: "https://github.com/assistant-ui/assistant-ui",
    adapter: "github-release-curated",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "planned",
    tags: ["assistant-ui"],
  },
  {
    id: "copilotkit-releases",
    name: "CopilotKit official updates",
    category,
    kind: "github-release",
    url: "https://github.com/CopilotKit/CopilotKit",
    adapter: "github-release-curated",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "planned",
    tags: ["copilotkit"],
  },

  // --- Planned: needs the generic HTML/JSON-LD adapter's per-source
  // selector config verified against real page structure, or no feed/API
  // was found at all after checking common conventions and autodiscovery
  // links live during onboarding. ---
  {
    id: "claude-blog",
    name: "Claude Blog",
    category,
    kind: "website",
    url: "https://claude.com/blog",
    adapter: "generic-html-json-ld",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "planned",
    tags: ["anthropic", "claude"],
  },
  {
    id: "anthropic-news",
    name: "Anthropic News",
    category,
    kind: "website",
    url: "https://www.anthropic.com/news",
    adapter: "generic-html-json-ld",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "planned",
    tags: ["anthropic"],
  },
  {
    id: "anthropic-engineering",
    name: "Anthropic Engineering",
    category,
    kind: "website",
    url: "https://www.anthropic.com/engineering",
    adapter: "generic-html-json-ld",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "planned",
    tags: ["anthropic", "engineering"],
  },
  {
    id: "openai-api-changelog",
    name: "OpenAI API changelog",
    category,
    kind: "api",
    // No dedicated changelog feed/JSON endpoint found distinct from the
    // mixed developers.openai.com/rss.xml stream (verified live: that feed
    // carries guides, videos, and cookbook examples, no changelog-only
    // items) — needs the official-api filters confirmed against a real
    // changelog response shape before activation.
    url: "https://platform.openai.com/docs/changelog",
    adapter: "official-api",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "planned",
    tags: ["openai"],
  },
  {
    id: "openai-codex-changelog",
    name: "OpenAI Codex changelog and developer posts",
    category,
    kind: "website",
    // developers.openai.com/codex/changelog redirected to a generic
    // ChatGPT changelog page during onboarding, not a confirmed
    // Codex-specific stream — needs the real URL reconfirmed.
    url: "https://developers.openai.com/codex/changelog",
    adapter: "generic-html-json-ld",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "planned",
    tags: ["openai", "codex"],
  },
  {
    id: "antigravity-blog",
    name: "Antigravity Blog",
    category,
    kind: "website",
    url: "https://antigravity.google/blog",
    adapter: "generic-html-json-ld",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "planned",
    tags: ["google", "antigravity"],
  },
  {
    id: "antigravity-cli-releases",
    name: "Antigravity CLI stable releases",
    category,
    kind: "website",
    // No public GitHub repo found for the Antigravity CLI during
    // onboarding — the product site's own /releases page is the
    // best-guess source until a github-release-eligible repo is confirmed.
    url: "https://antigravity.google/releases",
    adapter: "generic-html-json-ld",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "planned",
    tags: ["google", "antigravity"],
  },
  {
    id: "gemini-api-release-notes",
    name: "Gemini API release notes",
    category,
    kind: "website",
    url: "https://ai.google.dev/gemini-api/docs/changelog",
    adapter: "generic-html-json-ld",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "planned",
    tags: ["google", "gemini"],
  },
  {
    id: "mcp-blog",
    name: "Model Context Protocol Blog",
    category,
    kind: "website",
    // No blog section or feed found on the modelcontextprotocol.io docs
    // site during onboarding (Mintlify-based docs, no /blog route).
    url: "https://modelcontextprotocol.io",
    adapter: "generic-html-json-ld",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "planned",
    tags: ["mcp"],
  },
  {
    id: "cursor-blog",
    name: "Cursor Blog",
    category,
    kind: "website",
    url: "https://www.cursor.com/blog",
    adapter: "generic-html-json-ld",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "planned",
    tags: ["cursor"],
  },
  {
    id: "vercel-ai-sdk-blog",
    name: "Vercel AI SDK blog posts",
    category,
    kind: "website",
    // Returned HTTP 500 on every attempt during onboarding; needs
    // reconfirmation once the site is stable.
    url: "https://ai-sdk.dev/blog",
    adapter: "generic-html-json-ld",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "planned",
    tags: ["vercel", "ai-sdk"],
  },
  {
    id: "langchain-blog",
    name: "LangChain Blog",
    category,
    kind: "website",
    // blog.langchain.dev now redirects into the marketing site's blog
    // section, which carries no discoverable RSS/Atom feed.
    url: "https://www.langchain.com/blog",
    adapter: "generic-html-json-ld",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "planned",
    tags: ["langchain"],
  },
  {
    id: "llamaindex-blog",
    name: "LlamaIndex Blog",
    category,
    kind: "website",
    url: "https://www.llamaindex.ai/blog",
    adapter: "generic-html-json-ld",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "planned",
    tags: ["llamaindex"],
  },
  {
    id: "pinecone-learn",
    name: "Pinecone Learn",
    category,
    kind: "website",
    url: "https://www.pinecone.io/learn/",
    adapter: "generic-html-json-ld",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "planned",
    tags: ["vector-db", "pinecone"],
  },
  {
    id: "crewai-blog",
    name: "CrewAI Blog",
    category,
    kind: "website",
    url: "https://www.crewai.com/blog",
    adapter: "generic-html-json-ld",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "planned",
    tags: ["crewai", "agents"],
  },
];

export const referenceSources: ReferenceSource[] = [
  {
    id: "anthropic-claude-docs",
    name: "Anthropic/Claude docs",
    category,
    url: "https://docs.claude.com",
    note: "API and platform documentation, not a chronological event stream.",
  },
  {
    id: "openai-platform-docs",
    name: "OpenAI platform docs",
    category,
    url: "https://platform.openai.com/docs",
  },
  {
    id: "vercel-ai-sdk-docs",
    name: "Vercel AI SDK docs",
    category,
    url: "https://ai-sdk.dev/docs",
  },
  {
    id: "langchain-docs",
    name: "LangChain docs",
    category,
    url: "https://js.langchain.com/docs",
  },
  {
    id: "langgraph-docs",
    name: "LangGraph docs",
    category,
    url: "https://langchain-ai.github.io/langgraphjs/",
  },
  {
    id: "llamaindex-docs",
    name: "LlamaIndex docs",
    category,
    url: "https://docs.llamaindex.ai",
  },
  {
    id: "ollama-docs",
    name: "Ollama docs",
    category,
    url: "https://docs.ollama.com",
  },
  {
    id: "lm-studio-docs",
    name: "LM Studio docs",
    category,
    url: "https://lmstudio.ai/docs",
  },
  {
    id: "pinecone-docs",
    name: "Pinecone docs",
    category,
    url: "https://docs.pinecone.io",
    note: "Vector DB docs.",
  },
  {
    id: "weaviate-docs",
    name: "Weaviate docs",
    category,
    url: "https://weaviate.io/developers/weaviate",
    note: "Vector DB docs.",
  },
  {
    id: "qdrant-docs",
    name: "Qdrant docs",
    category,
    url: "https://qdrant.tech/documentation/",
    note: "Vector DB docs.",
  },
  {
    id: "chroma-docs",
    name: "Chroma docs",
    category,
    url: "https://docs.trychroma.com",
    note: "Vector DB docs.",
  },
  {
    id: "pgvector-docs",
    name: "pgvector docs",
    category,
    url: "https://github.com/pgvector/pgvector",
    note: "Vector DB docs (README-hosted).",
  },
  {
    id: "autogen-docs",
    name: "AutoGen docs",
    category,
    url: "https://microsoft.github.io/autogen/",
  },
  {
    id: "prompt-engineering-guide",
    name: "Prompt Engineering Guide",
    category,
    url: "https://www.promptingguide.ai",
  },
];
