import type { ReferenceSource, SourceConfig } from "../../shared/schemas/index.js";

export const category = "web-core" as const;

/**
 * Every source's cutoff below was approved as a single batch decision
 * (PRD §22) rather than guessed per source: 30 days back from onboarding,
 * enough real content on first sync without approaching the 200-item
 * volume guard (PRD §18.6).
 */
const INITIAL_SYNC_FROM = "2026-07-18";

export const sources: SourceConfig[] = [
  // --- Blogs (feed adapter) ---
  {
    id: "react-blog",
    name: "React Blog",
    category,
    kind: "feed",
    url: "https://react.dev/rss.xml",
    adapter: "feed",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "active",
    tags: ["react"],
  },
  {
    id: "overreacted",
    name: "Overreacted",
    category,
    kind: "feed",
    url: "https://overreacted.io/rss.xml",
    adapter: "feed",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "active",
    tags: ["react"],
  },
  {
    id: "nextjs-blog",
    name: "Next.js Blog",
    category,
    kind: "feed",
    url: "https://nextjs.org/feed.xml",
    adapter: "feed",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "active",
    tags: ["nextjs"],
  },
  {
    id: "vercel-blog",
    name: "Vercel Blog",
    category,
    kind: "feed",
    // Full blog feed (PRD §13.1 routing note): the Vercel Changelog is a
    // separate, DevOps-category source, never onboarded here.
    url: "https://vercel.com/blog/rss.xml",
    adapter: "feed",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "active",
    tags: ["vercel"],
  },
  {
    id: "tanstack-blog",
    name: "TanStack Portal/Blog",
    category,
    kind: "feed",
    url: "https://tanstack.com/rss.xml",
    adapter: "feed",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "active",
    tags: ["tanstack"],
  },
  {
    id: "tkdodo",
    name: "TkDodo",
    category,
    kind: "feed",
    url: "https://tkdodo.eu/blog/rss.xml",
    adapter: "feed",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "active",
    tags: ["react", "tanstack"],
  },
  {
    id: "typescript-blog",
    name: "TypeScript Blog",
    category,
    kind: "feed",
    url: "https://devblogs.microsoft.com/typescript/feed/",
    adapter: "feed",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "active",
    tags: ["typescript"],
  },
  {
    id: "mdn-blog",
    name: "MDN Blog",
    category,
    kind: "feed",
    url: "https://developer.mozilla.org/en-US/blog/rss.xml",
    adapter: "feed",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "active",
    tags: ["mdn", "web-standards"],
  },
  {
    id: "webdev-blog",
    name: "web.dev Blog",
    category,
    kind: "feed",
    url: "https://web.dev/blog/feed.xml",
    adapter: "feed",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "active",
    tags: ["web-performance"],
  },
  {
    id: "chrome-developers-blog",
    name: "Chrome Developers Blog",
    category,
    kind: "feed",
    url: "https://developer.chrome.com/blog/feed.xml",
    adapter: "feed",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "active",
    tags: ["chrome"],
  },
  {
    id: "addy-osmani",
    name: "Addy Osmani",
    category,
    kind: "feed",
    url: "https://addyosmani.com/feed.xml",
    adapter: "feed",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "active",
    tags: ["web-performance"],
  },
  {
    id: "speedcurve-blog",
    name: "SpeedCurve",
    category,
    kind: "feed",
    url: "https://www.speedcurve.com/blog/rss/",
    adapter: "feed",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "active",
    tags: ["web-performance"],
  },
  {
    id: "turborepo-blog",
    name: "Turborepo Blog",
    category,
    kind: "feed",
    url: "https://turborepo.dev/feed.xml",
    adapter: "feed",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "active",
    tags: ["build-tools"],
  },
  {
    id: "nx-blog",
    name: "Nx Blog",
    category,
    kind: "feed",
    url: "https://nx.dev/blog/rss.xml",
    adapter: "feed",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "active",
    tags: ["build-tools"],
  },
  {
    id: "moderncss-dev",
    name: "ModernCSS.dev",
    category,
    kind: "feed",
    url: "https://moderncss.dev/feed",
    adapter: "feed",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "active",
    tags: ["css"],
  },
  {
    id: "webkit-blog",
    name: "WebKit Blog",
    category,
    kind: "feed",
    url: "https://webkit.org/feed/",
    adapter: "feed",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "active",
    tags: ["web-standards"],
  },
  {
    id: "remix-blog",
    name: "Remix Blog",
    category,
    kind: "feed",
    url: "https://remix.run/blog/rss.xml",
    adapter: "feed",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "active",
    tags: ["remix", "react-router"],
  },

  // --- Stable releases (github-release adapter) ---
  {
    id: "react-releases",
    name: "React stable releases",
    category,
    kind: "github-release",
    url: "https://github.com/react/react",
    adapter: "github-release",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "active",
    tags: ["react"],
  },
  {
    id: "nextjs-releases",
    name: "Next.js stable releases",
    category,
    kind: "github-release",
    url: "https://github.com/vercel/next.js",
    adapter: "github-release",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "active",
    tags: ["nextjs"],
  },
  {
    id: "typescript-releases",
    name: "TypeScript stable releases",
    category,
    kind: "github-release",
    url: "https://github.com/microsoft/TypeScript",
    adapter: "github-release",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "active",
    tags: ["typescript"],
  },
  {
    id: "zustand-releases",
    name: "Zustand stable releases",
    category,
    kind: "github-release",
    url: "https://github.com/pmndrs/zustand",
    adapter: "github-release",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "active",
    tags: ["zustand", "state-management"],
  },
  {
    id: "react-router-releases",
    name: "React Router stable releases",
    category,
    kind: "github-release",
    url: "https://github.com/remix-run/react-router",
    adapter: "github-release",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "active",
    tags: ["react-router", "remix"],
  },

  // --- Planned: TanStack Query/Router/Table/Form/Virtual releases ---
  // Each repo publishes near-continuous per-package release tags (dozens
  // to 90+ in a 30-day window even after excluding drafts/prereleases) —
  // verified live against the GitHub API during onboarding. The existing
  // github-release adapter has no per-package curation, so activating
  // these as-is would either flood the feed with granular version-bump
  // noise or trip the volume guard outright. Needs a curated/filtered
  // release adapter, not yet built.
  {
    id: "tanstack-query-releases",
    name: "TanStack Query stable releases",
    category,
    kind: "github-release",
    url: "https://github.com/TanStack/query",
    adapter: "github-release-curated",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "planned",
    tags: ["tanstack", "react-query"],
  },
  {
    id: "tanstack-router-releases",
    name: "TanStack Router stable releases",
    category,
    kind: "github-release",
    url: "https://github.com/TanStack/router",
    adapter: "github-release-curated",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "planned",
    tags: ["tanstack"],
  },
  {
    id: "tanstack-table-releases",
    name: "TanStack Table stable releases",
    category,
    kind: "github-release",
    url: "https://github.com/TanStack/table",
    adapter: "github-release-curated",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "planned",
    tags: ["tanstack"],
  },
  {
    id: "tanstack-form-releases",
    name: "TanStack Form stable releases",
    category,
    kind: "github-release",
    url: "https://github.com/TanStack/form",
    adapter: "github-release-curated",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "planned",
    tags: ["tanstack"],
  },
  {
    id: "tanstack-virtual-releases",
    name: "TanStack Virtual stable releases",
    category,
    kind: "github-release",
    url: "https://github.com/TanStack/virtual",
    adapter: "github-release-curated",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "planned",
    tags: ["tanstack"],
  },

  // --- Planned: needs the RFC/proposal lifecycle adapter (#29) ---
  {
    id: "react-rfc-events",
    name: "React RFC events",
    category,
    kind: "github-event",
    url: "https://github.com/reactjs/rfcs",
    adapter: "rfc-lifecycle",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "planned",
    tags: ["react", "rfc"],
  },

  // --- Planned: needs the newsletter one-issue-per-item adapter (#30) ---
  {
    id: "javascript-weekly",
    name: "JavaScript Weekly",
    category,
    kind: "website",
    url: "https://javascriptweekly.com/issues",
    adapter: "newsletter",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "planned",
    tags: ["newsletter", "javascript"],
  },
  {
    id: "this-week-in-react",
    name: "This Week in React",
    category,
    kind: "website",
    // PRD §13.1 routing note: stays in Web Core, never duplicated in Mobile.
    url: "https://thisweekinreact.com/newsletter",
    adapter: "newsletter",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "planned",
    tags: ["newsletter", "react"],
  },
  {
    id: "frontend-focus",
    name: "Frontend Focus",
    category,
    kind: "website",
    url: "https://frontendfoc.us/issues",
    adapter: "newsletter",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "planned",
    tags: ["newsletter"],
  },
  {
    id: "css-weekly",
    name: "CSS Weekly",
    category,
    kind: "website",
    url: "https://css-weekly.com",
    adapter: "newsletter",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "planned",
    tags: ["newsletter", "css"],
  },

  // --- Planned: needs a generic HTML/JSON-LD adapter (#26); no feed found ---
  {
    id: "caniuse-news",
    name: "Can I Use news",
    category,
    kind: "website",
    url: "https://caniuse.com/ciu/news",
    adapter: "generic-html-json-ld",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "planned",
    tags: ["web-standards"],
  },
  {
    id: "module-federation-blog",
    name: "Module Federation Blog",
    category,
    kind: "website",
    url: "https://module-federation.io/blog/index.html",
    adapter: "generic-html-json-ld",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "planned",
    tags: ["module-federation"],
  },
  {
    id: "http-archive",
    name: "HTTP Archive",
    category,
    kind: "website",
    url: "https://httparchive.org",
    adapter: "generic-html-json-ld",
    initialSyncFrom: INITIAL_SYNC_FROM,
    status: "planned",
    tags: ["web-performance"],
  },
];

export const referenceSources: ReferenceSource[] = [];
